// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"meowchat-user/biz/adaptor"
	"meowchat-user/biz/application/service"
	"meowchat-user/biz/infrastructure/config"
	"meowchat-user/biz/infrastructure/mapper/likeMapper"
	"meowchat-user/biz/infrastructure/mapper/userMapper"
)

// Injectors from wire.go:

func NewUserServerImpl() (*adaptor.UserServerImpl, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	likeModel := likeMapper.NewLikeModel(configConfig)
	likeServiceImpl := &service.LikeServiceImpl{
		LikeModel: likeModel,
	}
	model := userMapper.NewModel(configConfig)
	userServiceImpl := &service.UserServiceImpl{
		UserModel: model,
	}
	userServerImpl := &adaptor.UserServerImpl{
		Config:      configConfig,
		LikeService: likeServiceImpl,
		UserService: userServiceImpl,
	}
	return userServerImpl, nil
}
